name = "bob-to-slack"
main = "src/main.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-03-29"


[[kv_namespaces]]
binding = "BobToSlack"
id = "b2f573ded4474502956a87ad1be95e13"
preview_id = "a0a8d34c42ff4ef18666ee128c508735"

[vars]
fields = "root.id,root.email,root.displayName,/work/title,personal.pronouns,work.customColumns.column_1693476959605"
bob_custom_level_column = "work.customColumns.column_1693476959605"
bob_custom_level_column_short = "column_1693476959605"
bob_endpoint = 'https://api.hibob.com/v1/people/'
slack_lookupemail_endpoint = 'https://slack.com/api/users.lookupByEmail'
slack_setuser_endpoint = 'https://slack.com/api/users.profile.set'
slack_title_field_id = 'Xf08HU7HLVM1'
slack_level_field_id = 'Xf08DNL0T80G'