name: Update Cloudflare Worker
on:
  push:
    branches: main

jobs:
  cloudflare-worker:
    name: Deploy Cloudflare Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            BASIC_AUTH
            SLACK_TOKEN
        env:
          BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
